// <auto-generated />
using JewerlyGala.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JewerlyGala.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JewerlyDbContext))]
    [Migration("20241109175326_itemModels")]
    partial class itemModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_ItemModel_id");

                    b.ToTable("ItemModel", (string)null);
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdModel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_ItemModelFeature_id");

                    b.ToTable("ItemModelFeature", (string)null);
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeatureLinkValue", b =>
                {
                    b.Property<int>("IdValue")
                        .HasColumnType("int");

                    b.Property<int>("IdFeature")
                        .HasColumnType("int");

                    b.HasKey("IdValue", "IdFeature")
                        .HasName("PK_ItemModelFeatureLinkValue_id");

                    b.HasIndex("IdFeature");

                    b.ToTable("ItemModelFeatureLinkValue", (string)null);
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ValueDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_ItemModelFeatureValue_id");

                    b.ToTable("ItemModelFeatureValue", (string)null);
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelLinkFeature", b =>
                {
                    b.Property<int>("IdModel")
                        .HasColumnType("int");

                    b.Property<int>("IdFeature")
                        .HasColumnType("int");

                    b.HasKey("IdModel", "IdFeature")
                        .HasName("PK_ItemModelLinkFeature_id");

                    b.HasIndex("IdFeature");

                    b.ToTable("ItemModelLinkFeature", (string)null);
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeatureLinkValue", b =>
                {
                    b.HasOne("JewerlyGala.Domain.Entities.ItemModelFeature", "Feature")
                        .WithMany("Values")
                        .HasForeignKey("IdFeature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyGala.Domain.Entities.ItemModelFeatureValue", "Value")
                        .WithMany("Features")
                        .HasForeignKey("IdValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelLinkFeature", b =>
                {
                    b.HasOne("JewerlyGala.Domain.Entities.ItemModelFeature", "Feature")
                        .WithMany("Models")
                        .HasForeignKey("IdFeature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JewerlyGala.Domain.Entities.ItemModel", "Model")
                        .WithMany("Features")
                        .HasForeignKey("IdModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModel", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeature", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("JewerlyGala.Domain.Entities.ItemModelFeatureValue", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
