# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost
@port = 7153

@JewerlyGala.API_HostAddress = https://localhost:7153
@refres = CfDJ8IAPeVFeqZlCoDkau0TXiv2tv8XHorDqlc3p1q3wOS6LHLAmsvwZu6NDqL7e5_RF5gX70YSmVue8BZk3_gec945OOAiOQMDQwH7zPBfpgnLeVQh8gFe9xxeExfKCJ48dOEjq3k7ODogD5UGxG181-cowElIuujzXiRzhjhx01G27QGuoUMvzcFhrTljgnf7lLuOakQ0AhTh4E_uGERxYKqLkIkcq-Pqy98wpncM2Mzl05Gkngp32It0iyLs4pAd6XbshxCPFKIEpr6CoqZup8JeDjbU00lWs0x7VkvIu0xTgF0l9PG8kDAvcWLOjsO4GdI94FzrGLQ6buuj4-zstpbE3ADM8dOlhv03CSDdUs9w9KGWtFFb4xuESYOM49af3jW2QJLJUOl3sJRjPs_GYxyoJ4VSya5EDCgB0tL75LRe5fnBhmo3plCJSXFF7p2buPkY8Cw5mIFiGGVQKz3PN6MIyV9ZZm89LnTivxHaDxHfmffJbsCiJ8JCm-NhsnSZl5vJiP9X12SGQq9WHtwiCnzBWnTeL3zKpNDAIxjHouKkU1q34eLpUtxwQ5Eri6M7YRQoY-hq1fnoNsC86czZuDk0BOwWPw0r0tsp1P49E52V1CdPDIkI97qMu5tolwzgRK2dRKPsqH4Nqvyn3iE_bOUW3U8yJQpko_mcaghuWlYRECer6kMwnDlE9byCGtR3ql_9IYRGirhC_3vjT0MFFMKsBYA_VR0uc-6eouEdn3SVsrHlStD7GdFvQc_iPm2sZDnH3OHMkEc7ONJ0DF9Q9G-lHNxO98YbEEpp3VqcvIycd

@token = CfDJ8IAPeVFeqZlCoDkau0TXiv1KnKKlezMD6tmfZQITLRhaS0KdnZjiuU3j3OHrHTGwgOYiMIVX66vTNjxVVHYq4Zoxxpxraav_1GGGpqG2Trj6ffDcnH1YG2Y3MkgkmHT9whmxqpXI6NP2NXVbCSkfKGRVQCTJFh0SUB7KVERbELV8t0m6bHLpn70h3_L2Jrdn_vT7ep3P5VlZ8ed0Q5wC4MOgTdbD0IFYnVy-Trknw1oexE72ooBo2ODEsWoi7hnEI4pLB3uGtwjIVYvd0tMMTFoRkbe2UyMa87_kvI7GP7slTtSNrdqANemyNEygFKX44cDy3xgwjVcqQ_FCll3AU4Z23Rg1lDhMQEFbwOype270BZTLF-brT3GLeyNAFOTWbd1HRjd1vo9c1WT1-Ezb0QKUQBlcsLesGsj930S8LGVKawrosigvEEBy1KIe8-i1fy-EvQIUaIEAFwlYvgJnZeWFmX0wZqGsuN9a5X8Wv6wHQAlWb-oYpyAtmITkrPmyKYXLuC2TIWUqhv96CMAWUagBoQoWSkpNSqTG6gLuS-ajHg7GZGjpeBKD8-Cq42N-Gb8W_MDWn5pj_OropRyQ0tDtiVn241vq5cmi8vrFD0pBUxtz2rWgLaaFPNQPPJMHt8nnvX_QHpNnVjVPpoCWB_l-QwcIHamAKECRz_yeubvyppt9ugfD-velsTQsxGqK17Nsj8zcMfqh6XvuHCJCmW6HWy-5pWrarAkhB2SV77NMhXs2meOCezyI-LIU13orDj3n3V2Uxz1B2KMm1Lty9LZJ2DlgiZWQ9JkqqlyCRT0t

POST {{JewerlyGala.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "admin@gala.com",
    "password": "C0nnect+1"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/identity/refresh
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "refreshToken": ""
}

###


POST {{JewerlyGala.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@gala.com",
    "password": "C0nnect+1"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie/fb3883d9-0fd5-4466-b54d-68f77b3b0113/features
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieId": "fb3883d9-0fd5-4466-b54d-68f77b3b0113",
  "feature": {
    "featureName": "Tipo broquel",
    "value": "Dormilonas"
  }
}

###





GET {{JewerlyGala.API_HostAddress}}/weatherforecast
Accept: application/json
ProjectUrl: {{$}}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel/1
Accept: application/json

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "name": "Test2"
}

###

PUT {{JewerlyGala.API_HostAddress}}/api/ItemModel/update
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "id": 3,
    "name": "Test2"
}

###


POST {{JewerlyGala.API_HostAddress}}/api/identity/user-role
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "admin@gmail.com",
  "roleName": "Admin"
}

###



POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieCode": "A202",
  "description": "Broqueles dormilones 4mm en oro 10k",
  "material": "Oro 10k",
  "quantity": 10,
  "supplierId": "62BF10A4-FF98-4F60-903A-3A2B6207186F",
  "purchaseUnitMeasure": "Item",
  "purchasePriceByUnitMeasure": 0,
  "purchaseDate": "2024-11-01",
  "purchaseUnitPrice": 1400,
  "salePercentRentability": 200,
  "saleUnitPrice": 2800,
  "featuresAndValues": [
    {
      "featureName": "Medida",
      "value": "4mm"
    }
  ]
}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemSerie
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "featuresAndValues": [
    {
      "featureName": "Tipo broquel",
      "value": "Dormilonas"
    },
    {
      "featureName": "Medida",
      "value": "2mm"
    }
  ]
}

###

PATCH {{JewerlyGala.API_HostAddress}}/api/ItemSerie/E350E349-207D-4F38-B990-7EF9EB035564
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "id": "E350E349-207D-4F38-B990-7EF9EB035564",
  "serieCode": "A304",
  "description": "Cadena cartier 3x1 de 40cm de largo por 3mm de grosor en plata 925",
  "material": "Plata 925",
  "quantity": 10,
  "supplierId": "62BF10A4-FF98-4F60-903A-3A2B6207186F",
  "purchaseUnitMeasure": "Item",
  "purchasePriceByUnitMeasure": 0,
  "purchaseDate": "2024-11-01",
  "purchaseUnitPrice": 900,
  "salePercentRentability": 200,
  "saleUnitPrice": 1800
}

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie/13A8BC7C-747C-42FF-A0AD-7640DF6B52C5/features
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieId": "13A8BC7C-747C-42FF-A0AD-7640DF6B52C5",
  "feature": {
    "featureName": "Tipo broquel",
    "value": "Dormilonas"
  }
}

###

DELETE {{JewerlyGala.API_HostAddress}}/api/ItemSerie/e08b8598-652a-4c77-a4f8-a9ca0467746f/features
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieId": "e08b8598-652a-4c77-a4f8-a9ca0467746E",
  "feature": {
    "featureName": "Medida",
    "value": "2mm"
  }
}

###
GET {{JewerlyGala.API_HostAddress}}/api/ItemSerie/fb3883d9-0fd5-4466-b54d-68f77b3b0113 
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{JewerlyGala.API_HostAddress}}/api/Customer/
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "name": "Cliente de pruebas 2",
  "phoneNumber": "1111111111",
  "email": "NA",
  "discount": 0
}
###

GET {{JewerlyGala.API_HostAddress}}/api/Customer/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{JewerlyGala.API_HostAddress}}/api/Customer/b4bcc000-6561-4c38-8921-0f4a7c867c45
Content-Type: application/json
Authorization: Bearer {{token}}
###

PATCH {{JewerlyGala.API_HostAddress}}/api/Customer/b4bcc000-6561-4c38-8921-0f4a7c867c45
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "customerId": "b4bcc000-6561-4c38-8921-0f4a7c867c45",
  "name": "Maricela Flores",
  "phoneNumber": "1111111111",
  "email": "NA",
  "discount": 0
}
###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "idCustomer": "28936c96-917f-419c-a38a-6288172f5435",
  "date": "2024-11-27",
  "zone": "Tianguis Lira"
}
###

GET {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61ee82b8-0f50-4b97-a7c7-b7a5b8d295d1
Content-Type: application/json
Authorization: Bearer {{token}}
###


POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61ee82b8-0f50-4b97-a7c7-b7a5b8d295d1/line
Content-Type: application/json       
Authorization: Bearer {{token}}
{
  "salesOrderId": "61ee82b8-0f50-4b97-a7c7-b7a5b8d295d1",
  "numLine": 3,
  "itemSerieId": "13A8BC7C-747C-42FF-A0AD-7640DF6B52C5",
  "quantity": 2
}
###


DELETE {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/line/E350E349-207D-4F38-B990-7EF9EB035564
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64",
  "itemSerieId": "E350E349-207D-4F38-B990-7EF9EB035564" ,
  "quantity": 2
}

  ###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1/step3Payment
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1",
  "paymentTerms": "PUE",
  "paymentMethod": "99",
  "paymentConditions": "NET07",
  "appliedOverAmoutToAccount": true,
  "payments": [
    {
      "idReceivingAccount": "7CBE1748-2424-4F12-9276-4985D28B66E7",
      "total": 12600,
      "paymentMethod": "01"
    }
  ],
  "paymentsDel": [
  ]
}

###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1/confirm
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1"
}

###

PATCH {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1/cancel
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "61EE82B8-0F50-4B97-A7C7-B7A5B8D295D1"
}
###

PATCH {{JewerlyGala.API_HostAddress}}/api/SalesOrder/61ee82b8-0f50-4b97-a7c7-b7a5b8d295d1/set-discount
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "61ee82b8-0f50-4b97-a7c7-b7a5b8d295d1",
  "discountPercentaje": 10
}