# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost
@port = 7153

@JewerlyGala.API_HostAddress = https://localhost:7153
@token = CfDJ8IAPeVFeqZlCoDkau0TXiv1SQ75s_xMK-TvVaQmhEAMeNR8qfeZ3mkRDoQxFx9gv3Mv_sFuftSZM9ieLiSgyKf83zfIVTxG8YtHqEe8-0Z6w4wEejsfCGwxgcC7KQ3GIIGkvg2Oz4-rz0whcbkhB8Iwxhu8RCy5YPaGRR74FR-LomqnCCmexujR8IJiNrwMx4gwyHZq9ioadIyfaGqGUcSgZAD5_SiUtIBeq8vtcG6KksoZjd_nDrokP4CUxHXuy_ucyl8LwQIIfcZX0RO_XXTwvQDUm00oI4HSffA_akB8s9_-1LendgpkalyoVPXGQkyOr-sTPRn9TQ7wprLZG4H0496IHhzusFP0F5p8bcG-yyiv_XhAZRnc2AM_Tx8OJ26VMfHj5ELF8WxumuivftU6NXerPtevrqX_paOq6eV4VU8kPey1IjbMFlDe0xvmLIM28hdbfnnoWppZOfRX5K6RmVjeLpAK6iX4RjDPcveqGK5Gv18Bb2kxmljSLcrBiJbvsz5pirIbQK5CQIa9uOo30WAMntbaLFliCu6Z4g2shsA_5YeBiOsq_8MzzvwF68h-055vnUVD8C6ZNvuLNeRlrlQMNoz_D7qBw-iEyQX3FadaZubNJOFwjJ6csamfECcep77E0FndzXa5oHGafXejGvXCkl1wZe1RWneXaEsWYXbGNJPitx8yxIZ0W6go7CExvDM3bmNkjJfOWmOwV72ZxtrtrypFrgGtrXv2jsKzNJN6x44rVSGirGiU0FujhAFAO1gL1Y3aqNlZULJcErD0uoi4ONbVs_DYdbZ4uAPk9v4CVPJRIhkbEjRlg5eNhrQuG_Dmr_L7zXwFMbKEXdRmmYNvf8ciVy2nkY7dFNGOoZQWnoyHBt5Gt5QPqe2iFsA


GET {{JewerlyGala.API_HostAddress}}/weatherforecast
Accept: application/json
ProjectUrl: {{$}}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel/1
Accept: application/json

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "name": "Test2"
}

###

PUT {{JewerlyGala.API_HostAddress}}/api/ItemModel/update
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "id": 3,
    "name": "Test2"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "C0nnect+1"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/identity/user-role
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "luis.martinezh13@gmail.com",
  "roleName": "Admin"
}

###



POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieCode": "A300",
  "description": "Cadena barbada de 45cm de largo por 4mm de grosor en plata 925",
  "material": "Plata 925",
  "quantity": 10,
  "supplierId": "AC87D593-8C05-4D40-AAC4-10FF5D217CC4",
  "purchaseUnitMeasure": "Item",
  "purchasePriceByUnitMeasure": 0,
  "purchaseDate": "2024-11-01",
  "purchaseUnitPrice": 900,
  "salePercentRentability": 200,
  "saleUnitPrice": 1800,
  "featuresAndValues": [
    {
      "featureName": "Tipo Cadena",
      "value": "Barbada"
    },
    {
      "featureName": "Largo",
      "value": "45cm"
    },
    {
      "featureName": "Grosor",
      "value": "4mm"
    }
  ]
}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemSerie/A6EA6A68-C290-4E1A-B986-C387D44406BD 
Content-Type: application/json
Authorization: Bearer {{token}}
