# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost
@port = 7153

@JewerlyGala.API_HostAddress = https://localhost:7153
@token = CfDJ8IAPeVFeqZlCoDkau0TXiv0G9WYjegi4lzvIqPbpHbNj7NFmNq605L6CR50P2XBcIwsSsiDMBlBvDJO0ZCF9GjcWyFOxMnYEkHcqX3YxEizl4fYgr7NzuD8OjkVeeTBXU10TrKxiF24DxjeBmc96ezypilsVC2BozJmLyum6J9iitaixGKMS9anZc_iTJSMO3Ulws5_WIp7VkyJixxybpidKZtntE6H3-zGvAE8sH2o2VUv0eQh2CjlFGkZN7Kumo2zgqYEcGcY0JInH86dgmr13TfExIzzCfWJYmfzUmFBM5aIH9PUgMOG7m_OZkQgeK_k1kvM3bDMLtlq8apyy-OZCfcGgi4un8_ROsZSta5qCDhvLxJ4c9tQwMm1X5LN42C6xaYKEkpsTX4qExNm3r7SXENgk8-mub98klBNNE0SqmGzMITxMo1k-R7tDM68fe4BrkNZRGkgTPwzKG5wi2m9DABb9iU0dx9_gVSW1usDcXa-q1KyOkofX-Nv_vYuLWuQ8SDyG0qkoIzuC999JYzPnAOE3gsLPM_Y1VRtkl9q4Bpqw7lelV63lrbNDuJQ1krB0wFhiCrFQ8Q5tbSTxNx9hkyywK5H-Epn6bPywzJASIn6Pbm746fotsdP0xmHhFfvd6aAIJtSKwQMEvRJ4--K8swxrxbwHwcZS8MIT3UVvrpx0UNeZD5E7uOexgbkf8TL3qw4K66G0qVKcPlyFglfcWLlKnCKj5lEP-XmbakKPN0q5yvbPV8CFkDcpSAUiwBHmYfbLNFJSkc6JlaNAV33AXsAe3NgUA8wlW_BxNYK5_EN-DQOcVb9Dg8vThqz7fEulvV3zs8Fp0RcRgTo_biz5TA2FCZcQsGjoWw5bGekdQYtEI5uwHdJ0WCm4dvpDsQ

GET {{JewerlyGala.API_HostAddress}}/weatherforecast
Accept: application/json
ProjectUrl: {{$}}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemModel/1
Accept: application/json

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemModel
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "name": "Test2"
}

###

PUT {{JewerlyGala.API_HostAddress}}/api/ItemModel/update
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "id": 3,
    "name": "Test2"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "C0nnect+1"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/identity/user-role
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userEmail": "luis.martinezh13@gmail.com",
  "roleName": "Admin"
}

###



POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieCode": "A200",
  "description": "Broqueles dormilones 2mm en oro 10k",
  "material": "Plata 925",
  "quantity": 10,
  "supplierId": "AC87D593-8C05-4D40-AAC4-10FF5D217CC4",
  "purchaseUnitMeasure": "Item",
  "purchasePriceByUnitMeasure": 0,
  "purchaseDate": "2024-11-01",
  "purchaseUnitPrice": 900,
  "salePercentRentability": 200,
  "saleUnitPrice": 1800,
  "featuresAndValues": [
    {
      "featureName": "Tipo Cadena",
      "value": "Cartier 3x1"
    },
    {
      "featureName": "Largo",
      "value": "40cm"
    },
    {
      "featureName": "Grosor",
      "value": "3mm"
    }
  ]
}

###

GET {{JewerlyGala.API_HostAddress}}/api/ItemSerie
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "featuresAndValues": [
    {
      "featureName": "Tipo broquel",
      "value": "Dormilonas"
    },
    {
      "featureName": "Medida",
      "value": "2mm"
    }
  ]
}

###

PATCH {{JewerlyGala.API_HostAddress}}/api/ItemSerie/E350E349-207D-4F38-B990-7EF9EB035564
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "id": "E350E349-207D-4F38-B990-7EF9EB035564",
  "serieCode": "A304",
  "description": "Cadena cartier 3x1 de 40cm de largo por 3mm de grosor en plata 925",
  "material": "Plata 925",
  "quantity": 10,
  "supplierId": "AC87D593-8C05-4D40-AAC4-10FF5D217CC4",
  "purchaseUnitMeasure": "Item",
  "purchasePriceByUnitMeasure": 0,
  "purchaseDate": "2024-11-01",
  "purchaseUnitPrice": 900,
  "salePercentRentability": 200,
  "saleUnitPrice": 1800
}

###

POST {{JewerlyGala.API_HostAddress}}/api/ItemSerie/e08b8598-652a-4c77-a4f8-a9ca0467746f/features
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieId": "e08b8598-652a-4c77-a4f8-a9ca0467746f",
  "feature": {
    "featureName": "Medida",
    "value": "2mm"
  }
}

###

DELETE {{JewerlyGala.API_HostAddress}}/api/ItemSerie/e08b8598-652a-4c77-a4f8-a9ca0467746f/features
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "serieId": "e08b8598-652a-4c77-a4f8-a9ca0467746E",
  "feature": {
    "featureName": "Medida",
    "value": "2mm"
  }
}

###
GET {{JewerlyGala.API_HostAddress}}/api/ItemSerie/A6EA6A68-C290-4E1A-B986-C387D44406BD 
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{JewerlyGala.API_HostAddress}}/api/Customer/
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "name": "Señora Mary",
  "phoneNumber": "1111111111",
  "email": "NA",
  "discount": 0
}
###

GET {{JewerlyGala.API_HostAddress}}/api/Customer/
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET {{JewerlyGala.API_HostAddress}}/api/Customer/b4bcc000-6561-4c38-8921-0f4a7c867c45
Content-Type: application/json
Authorization: Bearer {{token}}
###

PATCH {{JewerlyGala.API_HostAddress}}/api/Customer/b4bcc000-6561-4c38-8921-0f4a7c867c45
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "customerId": "b4bcc000-6561-4c38-8921-0f4a7c867c45",
  "name": "Maricela Flores",
  "phoneNumber": "1111111111",
  "email": "NA",
  "discount": 0
}
###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "idCustomer": "b4bcc000-6561-4c38-8921-0f4a7c867c45",
  "date": "2024-11-27",
  "zone": "Tianguis Lira"
}
###

GET {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64
Content-Type: application/json
Authorization: Bearer {{token}}
###


POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/line
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64",
  "numLine": 1,
  "itemSerieId": "E350E349-207D-4F38-B990-7EF9EB035564",
  "serieCode": "A304",
  "descripcion": "Cadena cartier 3x1 de 40cm de largo por 3mm de grosor en plata 925",
  "quantity": 2,
  "discountPercentaje": 10
}
###


DELETE {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/line/E350E349-207D-4F38-B990-7EF9EB035564
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64",
  "itemSerieId": "E350E349-207D-4F38-B990-7EF9EB035564" ,
  "quantity": 2
}

  ###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/step3Payment
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64",
  "paymentTerms": "PPD",
  "paymentMethod": "01",
  "paymentConditions": "NET07"
}

###

POST {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/confirm
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64",
  "paymentTerms": "PPD",
  "paymentMethod": "01",
  "paymentConditions": "NET07"
}

###

PATCH {{JewerlyGala.API_HostAddress}}/api/SalesOrder/23BF283A-1D71-46BC-B2B3-D638343A3F64/cancel
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "salesOrderId": "23BF283A-1D71-46BC-B2B3-D638343A3F64"
}